" [comment]: Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" [comment]: Enable type file detection.
"            Vim will be able to try to detect the type of file in use.
filetype on

" [comment]: Enable plugins and load plugin for the detected file type.
filetype plugin on

" [comment]: Load an indent file for the detected file type.
filetype indent on

" [comment]: Turn syntax highlighting on.
syntax on

" [comment]: Add numbers to each line on the left-hand side.
set number

" [comment]: Highlight cursor line underneath the cursor horizontally.
set cursorline

" [comment]: Highlight cursor line underneath the cursor vertically.
set cursorcolumn

" [comment]: Add a vertical line after 80 characters in the line.
set colorcolumn=80

" [comment]: Set shift width to 4 spaces.
set shiftwidth=4

" [comment]: Set tab width to 4 columns.
set tabstop=4

" [comment]: Use space characters instead of tabs.
set expandtab

" [comment]: Do not save backup files.
set nobackup

" [comment]: Don't let cursor scroll below or above N number of lines
"            when scrolling.
set scrolloff=10

" [comment]: Do not wrap lines. Allow long lines to extend
"            as far as the line goes.
set nowrap

" [commnet]: While searching though a file incrementally highlight
"            matching characters as you type.
set incsearch

" [comment]: Ignore capital letters during search.
set ignorecase

" [comment]: Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" [comment]: Show partial command you type in the last line of the screen.
set showcmd

" [comment]: Show the mode you are on the last line.
set showmode

" [comment]: Show matching words during a search.
set showmatch

" [comment]: Use highlighting when doing a search.
set hlsearch

" [comment]: Set the commands to save in history default number is 20.
set history=1000

" [comment]: Enable auto completion menu after pressing TAB.
set wildmenu

" [comment]: Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" [comment]: There are certain files that we would never want to edit with Vim.
"            Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" [comment]: Set the system clipboard.
set clipboard=unnamedplus
set clipboard+=unnamed


" PLUGINS ---------------------------------------------------------------- {{{
" [comment]: Install the 'vim-plug'.
call plug#begin('~/.vim/plugged')

" [comment]: 'Asynchronous Lint Engine (ALE)' Plugin.
Plug 'dense-analysis/ale'

" [comment]: 'The NERD Tree' Plugin.
Plug 'preservim/nerdtree'

" [comment]: Start NERDTree and put the cursor back in the other window.
autocmd VimEnter * NERDTree | wincmd p

call plug#end()

" }}}


" MAPPINGS --------------------------------------------------------------- {{{


" }}}


" VIMSCRIPT -------------------------------------------------------------- {{{

" [comment]: This will enable code folding.
"            Use the marker method of folding.
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" }}}


" STATUS LINE ------------------------------------------------------------ {{{


" }}}
